### ISSUE TITLE
Process N waits for ShareLock on transaction N; blocked by process

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#529]
This is a bug that we've seen a few times, but never tracked down how to fix it.

I filially saw it when running a command, here's the traceback:

Traceback (most recent call last):
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 11031 waits for ShareLock on transaction 14635008; blocked by process 11109.
Process 11109 waits for ShareLock on transaction 14634444; blocked by process 11031.
HINT:  See server log for query details.
CONTEXT:  while locking tuple (291,6) in relation "elections_post"
SQL statement "SELECT 1 FROM ONLY "public"."elections_post" x WHERE "ynr_id"::pg_catalog.text OPERATOR(pg_catalog.=) $1::pg_catalog.text FOR KEY SHARE OF x"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/www/wcivf/code/wcivf/apps/elections/management/commands/import_ballots.py", line 41, in handle
    importer.do_import()
  File "/var/www/wcivf/code/wcivf/apps/elections/import_helpers.py", line 161, in do_import
    self.add_ballots(page)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/db/transaction.py", line 240, in __exit__
    connection.commit()
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/wcivf/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: deadlock detected
DETAIL:  Process 11031 waits for ShareLock on transaction 14635008; blocked by process 11109.
Process 11109 waits for ShareLock on transaction 14634444; blocked by process 11031.
HINT:  See server log for query details.
CONTEXT:  while locking tuple (291,6) in relation "elections_post"
SQL statement "SELECT 1 FROM ONLY "public"."elections_post" x WHERE "ynr_id"::pg_catalog.text OPERATOR(pg_catalog.=) $1::pg_catalog.text FOR KEY SHARE OF x"

**Comment by chris48s** [comment]
:telescope: a rare sighting of the lesser spotted `DeadlockDetected` exception :bird:
